spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poc?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update


management:
  endpoints:
    web:
      exposure:
        include: "*"