spring:
  datasource:
    url: jdbc:mysql://10.104.165.74:3306/poc?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: poc
    password: poc

management:
  endpoints:
    web:
      exposure:
        include: "*"